"use client";
import React, { useState } from "react";
import Card from "./components/Card";

const Page = () => {
    const [country, setCountry] = useState("");
    const [category, setCategory] = useState("");
    const [sortBy, setSortBy] = useState("");
    const data = [
        {
            id: 1,
            title: "AI Blog",
            description:
                "This blog is generated by AI. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi quo quisquam, dolorem, quidem quas tenetur voluptate amet.",
        },
        {
            id: 2,
            title: "Web Development Trends",
            description:
                "Explore the latest web development trends including frameworks, AI integrations, and performance optimization techniques.",
        },
        {
            id: 3,
            title: "React Best Practices",
            description:
                "Learn how to structure large React apps, manage state effectively, and follow clean coding practices.",
        },
        {
            id: 4,
            title: "Node.js Performance Tips",
            description:
                "Improve your Node.js backend performance with caching, clustering, and optimized database queries.",
        },
        {
            id: 5,
            title: "Next.js for Beginners",
            description:
                "A step-by-step introduction to building SEO-friendly, scalable apps using Next.js and modern APIs.",
        },
        {
            id: 6,
            title: "MongoDB Essentials",
            description:
                "Understand MongoDB schema design, aggregation pipelines, and indexing strategies for performance.",
        },
        {
            id: 7,
            title: "Cloud Deployment Guide",
            description:
                "Learn how to deploy applications using AWS, Docker, and Kubernetes with CI/CD pipelines.",
        },
        {
            id: 8,
            title: "JavaScript Tricks",
            description:
                "Discover useful JavaScript tricks, ES6 features, and advanced concepts to write cleaner code.",
        },
        {
            id: 9,
            title: "UI/UX Design Principles",
            description:
                "Explore fundamental UI/UX principles to create user-friendly and responsive web applications.",
        },
        {
            id: 10,
            title: "Cybersecurity Basics",
            description:
                "A beginner-friendly guide to web application security, covering authentication, authorization, and data protection.",
        },
    ];


    return (
        <>
            {/* Filter Bar */}
            <div className="w-full bg-gray-800 flex flex-row sm:flex-row sm:items-center sm:justify-start px-5 py-3 gap-3 sm:gap-6 shadow-md flex-wrap">

                {/* Country Filter */}
                <form className="rounded-xl">
                    <select
                        id="countries"
                        value={country}
                        onChange={(e) => setCountry(e.target.value)}
                        className="w-28 sm:w-44 p-2 text-sm rounded-lg border border-gray-300 
              focus:outline-none focus:ring-2 focus:ring-blue-500 
              focus:border-blue-500 bg-gray-50 text-gray-900 
              dark:bg-gray-700 dark:border-gray-600 dark:text-white 
              dark:focus:ring-blue-400 transition"
                    >
                        <option value="">Filter by Country</option>
                        <option value="US">United States</option>
                        <option value="CA">Canada</option>
                        <option value="FR">France</option>
                        <option value="DE">Germany</option>
                    </select>
                </form>

                {/* Category Filter */}
                <form className="rounded-xl">
                    <select
                        id="category"
                        value={category}
                        onChange={(e) => setCategory(e.target.value)}
                        className="w-28 sm:w-44 p-2 text-sm rounded-lg border border-gray-300 
              focus:outline-none focus:ring-2 focus:ring-green-500 
              focus:border-green-500 bg-gray-50 text-gray-900 
              dark:bg-gray-700 dark:border-gray-600 dark:text-white 
              dark:focus:ring-green-400 transition"
                    >
                        <option value="">Filter by Category</option>
                        <option value="AI">AI</option>
                        <option value="ML">Machine Learning</option>
                        <option value="NLP">NLP</option>
                        <option value="Robotics">Robotics</option>
                    </select>
                </form>

                {/* Sort By Filter */}
                <form className="rounded-xl">
                    <select
                        id="sortBy"
                        value={sortBy}
                        onChange={(e) => setSortBy(e.target.value)}
                        className="w-28 sm:w-44 p-2 text-sm rounded-lg border border-gray-300 
              focus:outline-none focus:ring-2 focus:ring-purple-500 
              focus:border-purple-500 bg-gray-50 text-gray-900 
              dark:bg-gray-700 dark:border-gray-600 dark:text-white 
              dark:focus:ring-purple-400 transition"
                    >
                        <option value="">Sort By</option>
                        <option value="latest">Latest</option>
                        <option value="oldest">Oldest</option>
                        <option value="popular">Most Popular</option>
                    </select>
                </form>
            </div>

            {/* Blog Cards Section */}
            <div className="p-5 sm:p-10 grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-4 gap-6">
                {data.map((field) => (
                    <Card key={field.id} data={field} />
                ))}
            </div>

        </>
    );
};

export default Page;
